config/routes.rb
Rails.application.routes.draw do
  devise_for :players

  root                        'players#index'

  devise_scope :player do get '/players/sign_out' => 'devise/sessions#destroy' end

  resources :players,         only: [:edit, :update, :show, :create, :new, :index]
  resources :matches,         only: [:update, :show, :create, :new, :index]
  resources :teams,           only: [:edit, :update, :show, :create, :new, :index]
  resources :votes,           only: [:show, :create, :new, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :match
  has_many :votings
  has_many :player, through: :votings
  accepts_nested_attributes_for :votings

  validates_numericality_of :match_point, :less_than_or_equal_to => 10

  before_create :update_user_attrs

  private

    def update_user_attrs
      self.player_points.each do |player_id, attrs|
        player_votes_count = Vote.where(player_id: player_id).all.count

        player = Player.find player_id
        player.attack = calculate_new_scores(player.attack, player_votes_count, attrs["attack"])
        player.defense = calculate_new_scores(player.defense, player_votes_count, attrs["defense"])
        player.passion = calculate_new_scores(player.passion, player_votes_count, attrs["passion"])
        return false unless player.save
      end
    end

    def calculate_new_scores(previous_score, total_count, new_vote)
      new_score = ((previous_score * total_count) + calcuate_score_with_match_point(new_vote.to_f))/(total_count + 1)
    end

    def calcuate_score_with_match_point(vote)
      weighted_score = vote*(0.9 + self.match_point/100)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_player!
  before_action :set_vote, only: [:show, :edit, :update, :destroy]
  before_action :player_voted_check, only: [:new]
  before_action :player_played_check, only: [:new]
  before_action :admin?, without: [:new]


  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
    @players = (@current_match.team1.players + @current_match.team2.players).uniq
  end

  # # GET /votes/1/edit
  # def edit
  #   @players = (@current_match.team1.players + @current_match.team2.players).uniq
  # end

  # POST /votes
  # POST /votes.json
  def create
    params["vote"].permit!
    @vote = Vote.new(params["vote"])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /votes/1
  # # PATCH/PUT /votes/1.json
  # def update
  #   ap @vote
  #   raise
  #   params["vote"].permit!
  #   respond_to do |format|
  #     if @vote.update(params["vote"])
  #       format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @vote }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @vote.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /votes/1
  # # DELETE /votes/1.json
  # def destroy
  #   @vote.destroy
  #   respond_to do |format|
  #     format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:match_point, :player_points, :match_id, :player_id) 
    end

    def player_played_check
      unless (@current_match.team1.players + @current_match.team2.players).include?(current_player)
        flash[:info] = "C'mon man... You have not played in that match!"
        redirect_to :root
      end
    end

    def player_voted_check
      unless @current_match.votes.where(player_id: current_player.id).empty?
        flash[:info] = "You have already voted."
        redirect_to :root
      end
    end

    def admin?
      unless is_admin?
        flash[:info] = "You are not authorized."
        redirect_to :root
      end
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
  <div class="field">
    <%= label_tag :match_point %>
    <%= number_field_tag :match_point, nil, max: 10 %>
  </div>
  
  <%= render 'player_fields'%>

  <div class="field">
    <%= hidden_field_tag :match_id, @current_match.id.to_s, :class => 'vote_input' %>
  </div>

  <div class="field">
    <%= hidden_field_tag :player_id, current_player.id.to_s, :class => 'vote_input' %>
  </div>

  <div class="actions">
    <%= submit_tag "Submit", :class => 'submit' %>
  </div>

<script type="text/javascript">
  var player_points = {}
  var players = <%= raw(@players.to_json) %>
  var data_missing = false

  // $('.vote_input').change(function() {
  //   var $nonempty = $('.vote_input').filter(function() {
  //     return this.value = ''
  //   });
  //   console.log($nonempty)
  //   if ($nonempty.length > 0) {
  //     alert('empty')
  //   }
  //   else {
  //     $('.submit').prop("disabled", false);
  //   }
  // });

  $(".submit").on("click", function() {
    $('.vote_input').each(function( index ) {
      if(!$(this).val()) {
        data_missing = true
      }
    })
    if (!data_missing) {
      $('.players').each(function( index ) {
        var player_id = $(this).data().id
        var attr_type = $(this).data().type
        var val = $(this).val()
        if(player_points.hasOwnProperty(player_id)) {
          player_points[player_id][attr_type] = val
        }
        else {
          player_points[player_id] = {}
          player_points[player_id][attr_type] = val
        }
      });
      var vote_data = {
        "vote" : {
          "match_point": $('#match_point').val(),
          "match_id": $('#match_id').val(),
          "player_id": $('#player_id').val(),
          "player_points": player_points
        }
      };
      console.log(JSON.stringify(vote_data))
      $.ajax({
        url: "/votes",
        type: "POST",
        dataType: "json",
        data: vote_data,
        success: function(resp){ },
        error: function(err) {
          console.log(err)
        }
      });
    }
    else {
      console.log('data missing')
    }
  });
</script>

app/views/votes/_player_fields.html.erb
<% @players.each do |player| %>  
	<div>
	    <%= label_tag :id, player.id.to_s %>        
	    <%= hidden_field_tag :id, :value => player.id.to_s %>        
	    <br>
	    <%= label_tag :attack, "Attack" %>
	    <%= text_field_tag :attack, nil, :class => 'players vote_input', :data => {id: player.id.to_s, type: 'attack'} %>
	    <br>
	    <%= label_tag :defense, "Defense" %>
	    <%= text_field_tag :defense, nil, :class => 'players vote_input', :data => {id: player.id.to_s, type: 'defense'} %>
	    <br>
	    <%= label_tag :passion, "Passion" %>
	    <%= text_field_tag :passion, nil, :class => 'players vote_input', :data => {id: player.id.to_s, type: 'passion'}%>
	</div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Match point</th>
      <th>Player points</th>
      <th>Match</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.match_point %></td>
        <td><%= vote.player_points %></td>
        <td><%= vote.match %></td>
        <td><%= link_to 'Show', vote %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Match point:</strong>
  <%= @vote.match_point %>
</p>

<p>
  <strong>Player points:</strong>
  <%= @vote.player_points %>
</p>

<p>
  <strong>Match:</strong>
  <%= @vote.match %>
</p>

<%= link_to 'Back', votes_path %>